server:
  port: 8084

spring:
  application:
    name: billing-service

  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/doctor_db}

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

  stripe:
    secret-key: ${STRIPE_SECRET_KEY}

    webhook-secret: ${STRIPE_WEBHOOK_SECRET}